logging:
    level:
        root: DEBUG
        com.mytechnic.sample.persistence: DEBUG
        org.hibernate: INFO
        hibernate.SQL: DEBUG

mybatis:
    configuration.map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/**/*.xml

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: demo
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
        username: demo
    data.jpa.repositories.enabled: true